#include <stdio.h>
#include <stdlib.h>
#include <omp.h>

// ---------------------------------------------------------
// Recursive function using OpenMP Tasks
// ---------------------------------------------------------
int fib(int n) {
    int i, j;

    // OPTIMIZATION: The "Cutoff"
    // Task creation has overhead. If the work is too small, it is faster
    // to just do it serially rather than packaging it into a task box.
    if (n < 20) {
        if (n < 2) return n;
        return fib(n-1) + fib(n-2);
    }

    // Create a task to calculate fib(n-1)
    // We use shared(i) so the child task writes the result directly into 
    // the parent's variable 'i'
    #pragma omp task shared(i)
    {
        i = fib(n-1);
    }

    // Create a second task to calculate fib(n-2)
    #pragma omp task shared(j)
    {
        j = fib(n-2);
    }

    // CRITICAL: The parent thread cannot add i + j until both 
    // child tasks above have actually finished.
    #pragma omp taskwait

    return i + j;
}

// ---------------------------------------------------------
// Main Driver
// ---------------------------------------------------------
int main() {
    int n = 35; // Large enough to see parallel execution, small enough to finish fast
    int result;

    printf("Starting parallel Fibonacci(%d)...\n", n);
    double start = omp_get_wtime();

    // 1. Create the team of threads (The "Worker Pool")
    #pragma omp parallel
    {
        // 2. ONLY ONE thread should start the recursive tree.
        // If we didn't use 'single', every single thread would try to 
        // calculate fib(35) independently!
        #pragma omp single
        {
            printf("Root task generated by Thread %d\n", omp_get_thread_num());
            
            // This call generates the first two tasks, which generate four, etc.
            result = fib(n);
        } 
        // There is an implicit barrier at the end of 'single'. 
        // The rest of the threads will wait here, grabbing tasks from the 
        // pool until the entire tree is resolved.
    }

    double end = omp_get_wtime();

    printf("Result: Fibonacci(%d) = %d\n", n, result);
    printf("Execution Time: %f seconds\n", end - start);

    return 0;
}